name: "linkfish_genesis_stats" # cannot contain dots
version: "1.0.0" # should match coasti.yml and pyproject.toml

profile: "lfgs_duckdb" # needs to be found in `config/profiles.yml`

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# settings for model folders
models:
  linkfish_genesis_stats:
    +materialized: table

    stg:
      pystatis:
        +schema: stg_pystatis
    int:
      pystatis:
        +schema: int_pystatis

    mart:
      +schema: mart

    plmart:
      sup:
        +schema: plmart_sup

seeds:
    linkfish_genesis_stats:
        +schema: seed

        pystatis:
            +schema: seed_pystatis
