defaults:
    # Optionen für pystatis, siehe
    # https://correlaid.github.io/pystatis/pystatis.html#pystatis.table.Table.get_data
    prettify: true
    language: "de"
    quality: "off"
    startyear: null
    endyear: null
    regionalkey: "DG,010,01056*,01060*,01062*" # RKMerkmal

tables:
    - id: "11111-0002"
      output: "11111_0002_gebietsflaeche" # Basename der CSV
      description: "Gebietsflächen" # Beschreibung, endet im Header der CSV
      # Außerdem können pro Tabelle die default Einstellungen überschrieben werden

    - id: "12411-02-03-5"
      output: "12411_02_03_5_anzahl_einwohner_gemeinde"
      description: "Bevölkerungsstatistik Schleswig-Holstein"

    - id: "12411-07-01-4"
      output: "12411_07_01_4_durchschnittsalter_kreis"
      description: "Durchschnittsalter der Bevölkerung nach Kreisen und kreisfreien Städten"

    - id: "12411-07-01-5"
      output: "12411_07_01_5_durchschnittsalter_gemeinde"
      description: "Durchschnittsalter der Bevölkerung nach Gemeinden"

    - id: "12411-08-01-4"
      output: "12411_08_01_4_jugend_altenquotient_kreis"
      description: "Anzahl der Personen nach Altersklassen"

    - id: "12411-10-01-4"
      output: "12411_10_01_4_medianalter_kreis"
      description: "Medianalter"

    - id: "12612-01-01-4"
      output: "12612_01_01_4_lebendgeburten_kreis"
      description: "Anzahl der Lebendgeburten von Einwohner:innen pro Jahr, Zahl der Sterbefälle sowie deren Saldo"

    - id: "12613-01-01-4"
      output: "12613_01_01_4_sterbefaelle_kreis"
      description: "Sterbefälle pro Jahr je 1.000 Einwohner:innen"

    - id: "12711-01-03-4"
      output: "12711_01_03_4_wanderungen_kreis"
      description: "Zahl der Zuzüge/Wegzüge ins/aus dem Kreisgebiet und deren Saldo"

# die Genesis daten sind etwas clunky_benannt, aber Spaltennamen finden sich
# mitunter in verschiedenen Tabellen wieder
columns:
    - api: Stichtag # Spaltenname aus der API
      dbt: code_stichtag # Spaltenname in unserem DBT Projekt
      dtype: varchar(50) # dtype ist optional, varchar(50) ist der default.

    - api: Amtlicher Gemeindeschlüssel (AGS)__Code
      dbt: code_gemeinde

    - api: Amtlicher Gemeindeschlüssel (AGS)
      dbt: desc_gemeinde

    - api: Gebietsfläche__qkm
      dbt: fact_flaeche
      dtype: float

    - api: Geschlecht
      dbt: code_geschlecht # aber enthällt Werte wie "Insgesamt" | "männlich"

    # Alter
    - api: Altersgruppen (unter 3 bis 75 u. m.)
      dbt: code_altersgruppe_3_75 # aber enthällt Werte wie "6 bis unter 10 Jahre"

    - api: Altersgruppen (unter 18 bis 65 u. m.)
      dbt: code_altersgruppe_18_65

    - api: Durchschnittsalter der Bevölkerung__Jahre
      dbt: fact_alter_durchschnit
      dtype: float

    - api: Medianalter__Jahre
      dbt: fact_alter_median
      dtype: float

    # Quotienten
    - api: Altenquotient__Quotient
      dbt: fact_altenquotient
      dtype: float

    - api: Jugendquotient__Quotient
      dbt: fact_jugendquotient
      dtype: float

    # Anzahl Metriken
    - api: Bevölkerungsstand__Anzahl
      dbt: fact_count_bevoelkerungsstand
      dtype: int

    - api: Lebendgeborene__Anzahl
      dbt: fact_count_lebendgeborene
      dtype: int

    - api: Gestorbene__Anzahl
      dbt: fact_count_gestorbene
      dtype: int

    - api: Fortzüge über die Gemeindegrenzen__Anzahl
      dbt: fact_count_fortzuege
      dtype: int

    - api: Zuzüge über die Gemeindegrenzen__Anzahl
      dbt: fact_count_zuzuege
      dtype: int
